# Generated by Django 4.1.7 on 2023-03-17 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ramais',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('colaborador', models.CharField(max_length=100)),
                ('setor', models.CharField(max_length=100)),
                ('ramal', models.CharField(max_length=100)),
                ('area', models.CharField(max_length=30)),
                ('sala', models.CharField(max_length=30)),
                ('andarBloco', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Lista de Ramais',
                'verbose_name_plural': 'Lista de Ramais',
            },
        ),
    ]
